// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://difgbugfvmkjfhegzqdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZmdidWdmdm1ramZoZWd6cWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjM2NjIsImV4cCI6MjA2NTQ5OTY2Mn0.s4ny29XzYycvit6QGomUHN23zjufthb43szM4gPX-lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);